###########################################################################
# HITACHI VANTARA PROPRIETARY AND CONFIDENTIAL
# 
# Copyright 2002 - 2018 Hitachi Vantara. All rights reserved.
# 
# NOTICE: All information including source code contained herein is, and
# remains the sole property of Hitachi Vantara and its licensors. The intellectual
# and technical concepts contained herein are proprietary and confidential
# to, and are trade secrets of Hitachi Vantara and may be covered by U.S. and foreign
# patents, or patents in process, and are protected by trade secret and
# copyright laws. The receipt or possession of this source code and/or related
# information does not convey or imply any rights to reproduce, disclose or
# distribute its contents, or to manufacture, use, or sell anything that it
# may describe, in whole or in part. Any reproduction, modification, distribution,
# or public display of this information without the express written authorization
# from Hitachi Vantara is strictly prohibited and in violation of applicable laws and
# international treaties. Access to the source code contained herein is strictly
# prohibited to anyone except those individuals and entities who have executed
# confidentiality and non-disclosure agreements or other agreements with Hitachi Vantara,
# explicitly covering such access.
###########################################################################

# GET Method
Scenario Outline: <User> calls the web service to retrieve the list of generated content from the file <Path> within the <ContentUser> user's workspace directory.
	Given <User> has read permissions
	And the file <Path> exists
	And generated content from <Path> exists in the workspace directory: /home/<User>/workspace
	And <User> has access to the home and workspace directory of the user <ContentUser>
	When <User> calls the web service with the user query parameter value set to <ContentUser>
	Then the status code is 200
	And the response body contains "<creatorId>" + fileID + "</creatorId>" where the fileID is the Id of <Path>
Examples:
	| User | Path | ContentUser |
	| admin | /public/Steel Wheels/Sales Trend (multi-chart).xanalyzer | admin |
	| admin | /public/Steel Wheels/Sales Trend (multi-chart).xanalyzer | suzy |
	| admin | /home/admin/MyFile.xanalyzer | admin |
	| suzy | /public/Steel Wheels/Sales Trend (multi-chart).xanalyzer | suzy |
	| suzy | /public/Steel Wheels/Sales Trend (multi-chart).xanalyzer | pat |
	| suzy | /home/suzy/MyFile.xanalyzer | suzy |
	| admin | /public/!@#$%^&*()_-=+;:'"?<>,.`~[]{}|.xanalyzer | suzy |
	
Scenario: The user calls the web service to retrieve the list of generated content in JSON format from a file by another user.
	Given the user calling the web service has read permissions
	And the file exists
	And generated content from the file exists in the workspace directory of the user who generated the content.
	And the user calling the web service has access to the workspace directory of the user who generated the content.
	When the user calls the web service with the Accept header value "application/json" and the user query parameter value set to a different user
	Then the status code is 200
	And the response body contains the following followed by the file ID of the origin file:
		"creatorId":
		
Scenario: The user calls the web service to retrieve the list of generated content from a file by another user, but no content has been generated
	Given the user calling the web service has read permissions
	And the file exists
	And no content has been generated from the origin file
	When the user calls the web service with the user query parameter value set to a different user
	Then the status code is 200
	And the response body contains "<repositoryFileDtoes>"
	But the response body does not contain "<repositoryFileDto>"
		
Scenario: The user calls the web service to retrieve the list of content generated from a file that is located in a different user's home directory.
	Given the user calling the web service has read permissions
	And the file exists
	And the user calling the web service does not have access to the home directory that the file is located
	When the user calls the web service with the user query parameter value set to a different user
	Then the status code is 403
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files that have been generated by a file for a specified user, but does not have read permissions.
	Given the user alling the web service does not have read permissions
	And the file exists
	When the user calls the web service with the user query parameter value set to a different user
	Then the status code is 403.
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files generated from another file, but does not have access to content creator's home directory.
	Given the user calling the web service has read permissions
	And the user calling the web service does not have access to the content creator's home directory
	And the file exists
	When the user calls the web service with the user query parameter value set to a different user
	Then the status code is 403
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files generated from a non-existant file with invalid characters in its name.
	Given the user calling the web service has read permissions
	When the user calls the web service with the user query parameter value set to a different user
	Then the status code is 400
	And the response body does not contain "<repositoryFileDtoes>"
Examples:
	| pathId | User |
	| :home:admin:/.prpt | admin |
	| :home:admin:\.prpt | admin |
	
Scenario: The user calls the web service to retrieve a list of files generated from another file, but does not include the user query parameter.
	Given the user calling the web service has read permissions
	And the file exists
	When the user calls the web service without using the "user" query parameter
	Then the status code is 400
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files generated from another file, but does not specify a value for the query parameter.
	Given the user calling the web service has read permissions
	And the file exists
	When the user calls the web service with the "user" query parameter, but no value specified
	Then the status code is 400
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files generated from another file that does not exist.
	Given the user calling the web service has read permissions
	And the file does not exist
	When the user calls the web service with the user query parameter value set to a different user
	Then the status code is 404
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The anonymous user calls the web service to retrieve the list of files generated from another file.
	Given the file exists
	When the anonymous user calls the web service with the user query parameter value set to a different user
	Then the status code is 401
	And the response body does not contain "<repositoryFileDtoes>"