###########################################################################
# HITACHI VANTARA PROPRIETARY AND CONFIDENTIAL
# 
# Copyright 2002 - 2018 Hitachi Vantara. All rights reserved.
# 
# NOTICE: All information including source code contained herein is, and
# remains the sole property of Hitachi Vantara and its licensors. The intellectual
# and technical concepts contained herein are proprietary and confidential
# to, and are trade secrets of Hitachi Vantara and may be covered by U.S. and foreign
# patents, or patents in process, and are protected by trade secret and
# copyright laws. The receipt or possession of this source code and/or related
# information does not convey or imply any rights to reproduce, disclose or
# distribute its contents, or to manufacture, use, or sell anything that it
# may describe, in whole or in part. Any reproduction, modification, distribution,
# or public display of this information without the express written authorization
# from Hitachi Vantara is strictly prohibited and in violation of applicable laws and
# international treaties. Access to the source code contained herein is strictly
# prohibited to anyone except those individuals and entities who have executed
# confidentiality and non-disclosure agreements or other agreements with Hitachi Vantara,
# explicitly covering such access.
###########################################################################

# GET Method

#The file Id can be found using the properties endpoint.
Scenario Outline: <User> calls the web service to retrieve a list of files that have been generated by the file <Path>.
	Given <User> has read permissions
	And the file <Path> exists
	And generated content from <Path> exists in the workspace directory: /home/<User>/workspace
	When the user calls the web service
	Then the status code is 200
	And the response body contains "<creatorId>" + fileID + "</creatorId>" where the fileID is the Id of <Path>
Examples:
	| User | Path |
	| admin | /home/admin/myFile.xanalyzer |
	| admin | /public/Steel Wheels/Sales Trend (multi-chart).xanalyzer |
	| suzy | /home/suzy/myFile.xanalyzer |
	| suzy | /public/Steel Wheels/Sales Trend (multi-chart).xanalyzer |
	| admin | /home/admin/!@#$%^&*()_-=+;:'"?<>,.`~[]{}|.xanalyzer |
	
Scenario: The user calls the web service to retrieve a list of files in JSON format that have been generated by another file.
	Given the user has read permissions
	And the file exists
	And generated content from the origin file exists in the user's workspace directory
	When the user calls the web service with the Accept header value "application/json"
	Then the status code is 200
	And the response body contains the following followed by the file ID of the origin file:
		"creatorId":
		
Scenario: The user calls the web service to retrieve a list of files that have been generated by another file, but no content has been generated
	Given the user has read permissions
	And the file exists
	And no content has been generated from the origin file
	When the user calls the web service
	Then the status code is 200
	And the response body contains "<repositoryFileDtoes>"
	But the response body does not contain "<repositoryFileDto>"
		
Scenario: The user calls the web service to retrieve a list of files that have been gerated by a file that exists in another user's directory.
	Given the user has read permissions
	And the file exists
	And the user calling the web service does not have access to the other user's home directory
	When the user calls the web service
	Then the status code is 403
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files that have been generated by a file, but does not have read permissions.
	Given the user does not have read permissions
	And the file exists
	When the user calls the web service
	Then the status code is 403.
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files that have been generated by a non-existant file with invalid characters in its name.
	Given the user has read permissions
	When the user calls the web service
	Then the status code is 400
	And the response body does not contain "<repositoryFileDtoes>"
Examples:
	| pathId |
	| :home:admin:/.prpt |
	| :home:admin:\.prpt |

Scenario: The anonymous user calls the web service to retrieve a list of files that have been generated by a file.
	Given the file exists
	When the anonymous user calls the web service
	Then the status code is 401
	And the response body does not contain "<repositoryFileDtoes>"
	
Scenario: The user calls the web service to retrieve a list of files that have been generated by a file that doesn't exist.
	Given the file does not exist
	And the user has read permissions
	When the user calls the web service
	Then the status code is 404
	And the response body does not contain "<repositoryFileDtoes>"